import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#fff1f7',
          100: '#ffe1ee',
          500: '#ec4899',
          600: '#db2777',
          700: '#be185d',
        },
        'glow-primary': '#576500',
        'glow-primary-container': '#9bb01c',
        'glow-on-primary': '#ffffff',
        'glow-on-primary-container': '#374000',
        'glow-secondary': '#a53b29',
        'glow-secondary-container': '#fe7d66',
        'glow-on-secondary': '#ffffff',
        'glow-tertiary': '#006874',
        'glow-tertiary-container': '#4db4c3',
        'glow-on-tertiary': '#ffffff',
        'glow-on-tertiary-container': '#00434a',
        'glow-surface': '#f6faff',
        'glow-surface-dim': '#d3dbe3',
        'glow-surface-container-lowest': '#ffffff',
        'glow-surface-container-low': '#edf4fd',
        'glow-surface-container': '#e7eff7',
        'glow-surface-container-high': '#e1e9f1',
        'glow-surface-container-highest': '#dbe3ec',
        'glow-on-surface': '#151c22',
        'glow-on-surface-variant': '#464836',
        'glow-outline': '#777964',
        'glow-outline-variant': '#c7c8b0',
        'glow-primary-fixed': '#d7ee59',
        'glow-primary-fixed-dim': '#bbd13f',
        'glow-error': '#ba1a1a',
        'glow-error-container': '#ffdad6',
        'glow-surface-variant': '#dbe3ec',
        'glow-inverse-surface': '#293138',
        'glow-inverse-on-surface': '#eaf2fa',
      },
      fontFamily: {
        jakarta: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      boxShadow: {
        soft: '0 12px 30px rgba(15, 23, 42, 0.08)',
        ambient: '0px 24px 48px rgba(21, 28, 34, 0.06)',
      },
    },
  },
  plugins: [],
} satisfies Config;
